# version: "3.1"

services:
  galeria:
    container_name: galeria
    # Debe ser el name usado en el action de GH
    image: pandgri859/devops02:latest
    ports:
      - 80:5000
    restart: always
